//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.DungWCFQuanLyXeMay {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eNhanVien", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eNhanVien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChucVuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CmndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaNhanVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoDienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNhanVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrangthaiNVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChucVu {
            get {
                return this.ChucVuField;
            }
            set {
                if ((object.ReferenceEquals(this.ChucVuField, value) != true)) {
                    this.ChucVuField = value;
                    this.RaisePropertyChanged("ChucVu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cmnd {
            get {
                return this.CmndField;
            }
            set {
                if ((object.ReferenceEquals(this.CmndField, value) != true)) {
                    this.CmndField = value;
                    this.RaisePropertyChanged("Cmnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaNhanVien {
            get {
                return this.MaNhanVienField;
            }
            set {
                if ((object.ReferenceEquals(this.MaNhanVienField, value) != true)) {
                    this.MaNhanVienField = value;
                    this.RaisePropertyChanged("MaNhanVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoDienThoai {
            get {
                return this.SoDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoDienThoaiField, value) != true)) {
                    this.SoDienThoaiField = value;
                    this.RaisePropertyChanged("SoDienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNhanVien {
            get {
                return this.TenNhanVienField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNhanVienField, value) != true)) {
                    this.TenNhanVienField = value;
                    this.RaisePropertyChanged("TenNhanVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrangthaiNV {
            get {
                return this.TrangthaiNVField;
            }
            set {
                if ((object.ReferenceEquals(this.TrangthaiNVField, value) != true)) {
                    this.TrangthaiNVField = value;
                    this.RaisePropertyChanged("TrangthaiNV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eKhachHang", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eKhachHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CmndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhachHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoDienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKhachHangField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cmnd {
            get {
                return this.CmndField;
            }
            set {
                if ((object.ReferenceEquals(this.CmndField, value) != true)) {
                    this.CmndField = value;
                    this.RaisePropertyChanged("Cmnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaKhachHang {
            get {
                return this.MaKhachHangField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhachHangField, value) != true)) {
                    this.MaKhachHangField = value;
                    this.RaisePropertyChanged("MaKhachHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoDienThoai {
            get {
                return this.SoDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoDienThoaiField, value) != true)) {
                    this.SoDienThoaiField = value;
                    this.RaisePropertyChanged("SoDienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenKhachHang {
            get {
                return this.TenKhachHangField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKhachHangField, value) != true)) {
                    this.TenKhachHangField = value;
                    this.RaisePropertyChanged("TenKhachHang");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eXeMay", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eXeMay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float GiaThanhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoaiBanhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoaiPhanhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaXeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MauSacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhanKhoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenXeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrangThaiXeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float GiaThanh {
            get {
                return this.GiaThanhField;
            }
            set {
                if ((this.GiaThanhField.Equals(value) != true)) {
                    this.GiaThanhField = value;
                    this.RaisePropertyChanged("GiaThanh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoaiBanh {
            get {
                return this.LoaiBanhField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiBanhField, value) != true)) {
                    this.LoaiBanhField = value;
                    this.RaisePropertyChanged("LoaiBanh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoaiPhanh {
            get {
                return this.LoaiPhanhField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiPhanhField, value) != true)) {
                    this.LoaiPhanhField = value;
                    this.RaisePropertyChanged("LoaiPhanh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLoaiField, value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaXe {
            get {
                return this.MaXeField;
            }
            set {
                if ((object.ReferenceEquals(this.MaXeField, value) != true)) {
                    this.MaXeField = value;
                    this.RaisePropertyChanged("MaXe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MauSac {
            get {
                return this.MauSacField;
            }
            set {
                if ((object.ReferenceEquals(this.MauSacField, value) != true)) {
                    this.MauSacField = value;
                    this.RaisePropertyChanged("MauSac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhanKhoi {
            get {
                return this.PhanKhoiField;
            }
            set {
                if ((object.ReferenceEquals(this.PhanKhoiField, value) != true)) {
                    this.PhanKhoiField = value;
                    this.RaisePropertyChanged("PhanKhoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenXe {
            get {
                return this.TenXeField;
            }
            set {
                if ((object.ReferenceEquals(this.TenXeField, value) != true)) {
                    this.TenXeField = value;
                    this.RaisePropertyChanged("TenXe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrangThaiXe {
            get {
                return this.TrangThaiXeField;
            }
            set {
                if ((object.ReferenceEquals(this.TrangThaiXeField, value) != true)) {
                    this.TrangThaiXeField = value;
                    this.RaisePropertyChanged("TrangThaiXe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eLoaiXe", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eLoaiXe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLoaiField, value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoai {
            get {
                return this.TenLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiField, value) != true)) {
                    this.TenLoaiField = value;
                    this.RaisePropertyChanged("TenLoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eHoaDon", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eHoaDon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaHoaDonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKhachHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaNhanVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayLapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrangThaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaHoaDon {
            get {
                return this.MaHoaDonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaHoaDonField, value) != true)) {
                    this.MaHoaDonField = value;
                    this.RaisePropertyChanged("MaHoaDon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaKhachHang {
            get {
                return this.MaKhachHangField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKhachHangField, value) != true)) {
                    this.MaKhachHangField = value;
                    this.RaisePropertyChanged("MaKhachHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaNhanVien {
            get {
                return this.MaNhanVienField;
            }
            set {
                if ((object.ReferenceEquals(this.MaNhanVienField, value) != true)) {
                    this.MaNhanVienField = value;
                    this.RaisePropertyChanged("MaNhanVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayLap {
            get {
                return this.NgayLapField;
            }
            set {
                if ((this.NgayLapField.Equals(value) != true)) {
                    this.NgayLapField = value;
                    this.RaisePropertyChanged("NgayLap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TrangThaiField, value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eThongKeBanChay", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eThongKeBanChay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoaiBanhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoaiPhanhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaXeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MauSacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhanKhoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenXeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoaiBanh {
            get {
                return this.LoaiBanhField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiBanhField, value) != true)) {
                    this.LoaiBanhField = value;
                    this.RaisePropertyChanged("LoaiBanh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoaiPhanh {
            get {
                return this.LoaiPhanhField;
            }
            set {
                if ((object.ReferenceEquals(this.LoaiPhanhField, value) != true)) {
                    this.LoaiPhanhField = value;
                    this.RaisePropertyChanged("LoaiPhanh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaXe {
            get {
                return this.MaXeField;
            }
            set {
                if ((object.ReferenceEquals(this.MaXeField, value) != true)) {
                    this.MaXeField = value;
                    this.RaisePropertyChanged("MaXe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MauSac {
            get {
                return this.MauSacField;
            }
            set {
                if ((object.ReferenceEquals(this.MauSacField, value) != true)) {
                    this.MauSacField = value;
                    this.RaisePropertyChanged("MauSac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhanKhoi {
            get {
                return this.PhanKhoiField;
            }
            set {
                if ((object.ReferenceEquals(this.PhanKhoiField, value) != true)) {
                    this.PhanKhoiField = value;
                    this.RaisePropertyChanged("PhanKhoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoai {
            get {
                return this.TenLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiField, value) != true)) {
                    this.TenLoaiField = value;
                    this.RaisePropertyChanged("TenLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenXe {
            get {
                return this.TenXeField;
            }
            set {
                if ((object.ReferenceEquals(this.TenXeField, value) != true)) {
                    this.TenXeField = value;
                    this.RaisePropertyChanged("TenXe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eThongKeKhachMuaNhieu", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eThongKeKhachMuaNhieu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CmndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayMuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenXeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cmnd {
            get {
                return this.CmndField;
            }
            set {
                if ((object.ReferenceEquals(this.CmndField, value) != true)) {
                    this.CmndField = value;
                    this.RaisePropertyChanged("Cmnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKHField, value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayMua {
            get {
                return this.NgayMuaField;
            }
            set {
                if ((this.NgayMuaField.Equals(value) != true)) {
                    this.NgayMuaField = value;
                    this.RaisePropertyChanged("NgayMua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SDT {
            get {
                return this.SDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SDTField, value) != true)) {
                    this.SDTField = value;
                    this.RaisePropertyChanged("SDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenKH {
            get {
                return this.TenKHField;
            }
            set {
                if ((object.ReferenceEquals(this.TenKHField, value) != true)) {
                    this.TenKHField = value;
                    this.RaisePropertyChanged("TenKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenXe {
            get {
                return this.TenXeField;
            }
            set {
                if ((object.ReferenceEquals(this.TenXeField, value) != true)) {
                    this.TenXeField = value;
                    this.RaisePropertyChanged("TenXe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eThongKeDoanhThu", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eThongKeDoanhThu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GiaBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayLapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenXeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ThueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GiaBan {
            get {
                return this.GiaBanField;
            }
            set {
                if ((this.GiaBanField.Equals(value) != true)) {
                    this.GiaBanField = value;
                    this.RaisePropertyChanged("GiaBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayLap {
            get {
                return this.NgayLapField;
            }
            set {
                if ((this.NgayLapField.Equals(value) != true)) {
                    this.NgayLapField = value;
                    this.RaisePropertyChanged("NgayLap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoai {
            get {
                return this.TenLoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiField, value) != true)) {
                    this.TenLoaiField = value;
                    this.RaisePropertyChanged("TenLoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenXe {
            get {
                return this.TenXeField;
            }
            set {
                if ((object.ReferenceEquals(this.TenXeField, value) != true)) {
                    this.TenXeField = value;
                    this.RaisePropertyChanged("TenXe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Thue {
            get {
                return this.ThueField;
            }
            set {
                if ((this.ThueField.Equals(value) != true)) {
                    this.ThueField = value;
                    this.RaisePropertyChanged("Thue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eChiTiet", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class eChiTiet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float GiaBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaHoaDonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaXeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ThueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float GiaBan {
            get {
                return this.GiaBanField;
            }
            set {
                if ((this.GiaBanField.Equals(value) != true)) {
                    this.GiaBanField = value;
                    this.RaisePropertyChanged("GiaBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaHoaDon {
            get {
                return this.MaHoaDonField;
            }
            set {
                if ((object.ReferenceEquals(this.MaHoaDonField, value) != true)) {
                    this.MaHoaDonField = value;
                    this.RaisePropertyChanged("MaHoaDon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaXe {
            get {
                return this.MaXeField;
            }
            set {
                if ((object.ReferenceEquals(this.MaXeField, value) != true)) {
                    this.MaXeField = value;
                    this.RaisePropertyChanged("MaXe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Thue {
            get {
                return this.ThueField;
            }
            set {
                if ((this.ThueField.Equals(value) != true)) {
                    this.ThueField = value;
                    this.RaisePropertyChanged("Thue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DungWCFQuanLyXeMay.IQuanLyXeMay")]
    public interface IQuanLyXeMay {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/LayToanBoNhanVien", ReplyAction="http://tempuri.org/IQuanLyXeMay/LayToanBoNhanVienResponse")]
        Presentation.DungWCFQuanLyXeMay.eNhanVien[] LayToanBoNhanVien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/LayToanBoNhanVien", ReplyAction="http://tempuri.org/IQuanLyXeMay/LayToanBoNhanVienResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eNhanVien[]> LayToanBoNhanVienAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/ThemNhanVien", ReplyAction="http://tempuri.org/IQuanLyXeMay/ThemNhanVienResponse")]
        int ThemNhanVien(Presentation.DungWCFQuanLyXeMay.eNhanVien nv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/ThemNhanVien", ReplyAction="http://tempuri.org/IQuanLyXeMay/ThemNhanVienResponse")]
        System.Threading.Tasks.Task<int> ThemNhanVienAsync(Presentation.DungWCFQuanLyXeMay.eNhanVien nv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/KiemTraNhanVien", ReplyAction="http://tempuri.org/IQuanLyXeMay/KiemTraNhanVienResponse")]
        bool KiemTraNhanVien(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/KiemTraNhanVien", ReplyAction="http://tempuri.org/IQuanLyXeMay/KiemTraNhanVienResponse")]
        System.Threading.Tasks.Task<bool> KiemTraNhanVienAsync(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/SuaNhanVien", ReplyAction="http://tempuri.org/IQuanLyXeMay/SuaNhanVienResponse")]
        int SuaNhanVien(Presentation.DungWCFQuanLyXeMay.eNhanVien nv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/SuaNhanVien", ReplyAction="http://tempuri.org/IQuanLyXeMay/SuaNhanVienResponse")]
        System.Threading.Tasks.Task<int> SuaNhanVienAsync(Presentation.DungWCFQuanLyXeMay.eNhanVien nv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/XoaNhanVien", ReplyAction="http://tempuri.org/IQuanLyXeMay/XoaNhanVienResponse")]
        int XoaNhanVien(Presentation.DungWCFQuanLyXeMay.eNhanVien nv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/XoaNhanVien", ReplyAction="http://tempuri.org/IQuanLyXeMay/XoaNhanVienResponse")]
        System.Threading.Tasks.Task<int> XoaNhanVienAsync(Presentation.DungWCFQuanLyXeMay.eNhanVien nv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/LayToanBoKhachHang", ReplyAction="http://tempuri.org/IQuanLyXeMay/LayToanBoKhachHangResponse")]
        Presentation.DungWCFQuanLyXeMay.eKhachHang[] LayToanBoKhachHang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/LayToanBoKhachHang", ReplyAction="http://tempuri.org/IQuanLyXeMay/LayToanBoKhachHangResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eKhachHang[]> LayToanBoKhachHangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/ThemKhachHang", ReplyAction="http://tempuri.org/IQuanLyXeMay/ThemKhachHangResponse")]
        int ThemKhachHang(Presentation.DungWCFQuanLyXeMay.eKhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/ThemKhachHang", ReplyAction="http://tempuri.org/IQuanLyXeMay/ThemKhachHangResponse")]
        System.Threading.Tasks.Task<int> ThemKhachHangAsync(Presentation.DungWCFQuanLyXeMay.eKhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/SuaKhachHang", ReplyAction="http://tempuri.org/IQuanLyXeMay/SuaKhachHangResponse")]
        int SuaKhachHang(Presentation.DungWCFQuanLyXeMay.eKhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/SuaKhachHang", ReplyAction="http://tempuri.org/IQuanLyXeMay/SuaKhachHangResponse")]
        System.Threading.Tasks.Task<int> SuaKhachHangAsync(Presentation.DungWCFQuanLyXeMay.eKhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/XoaKhachHang", ReplyAction="http://tempuri.org/IQuanLyXeMay/XoaKhachHangResponse")]
        int XoaKhachHang(Presentation.DungWCFQuanLyXeMay.eKhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/XoaKhachHang", ReplyAction="http://tempuri.org/IQuanLyXeMay/XoaKhachHangResponse")]
        System.Threading.Tasks.Task<int> XoaKhachHangAsync(Presentation.DungWCFQuanLyXeMay.eKhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/KiemTraKhachHang", ReplyAction="http://tempuri.org/IQuanLyXeMay/KiemTraKhachHangResponse")]
        bool KiemTraKhachHang(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/KiemTraKhachHang", ReplyAction="http://tempuri.org/IQuanLyXeMay/KiemTraKhachHangResponse")]
        System.Threading.Tasks.Task<bool> KiemTraKhachHangAsync(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/LayToanBoXeMay", ReplyAction="http://tempuri.org/IQuanLyXeMay/LayToanBoXeMayResponse")]
        Presentation.DungWCFQuanLyXeMay.eXeMay[] LayToanBoXeMay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/LayToanBoXeMay", ReplyAction="http://tempuri.org/IQuanLyXeMay/LayToanBoXeMayResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eXeMay[]> LayToanBoXeMayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/LayToanBoLoaiXe", ReplyAction="http://tempuri.org/IQuanLyXeMay/LayToanBoLoaiXeResponse")]
        Presentation.DungWCFQuanLyXeMay.eLoaiXe[] LayToanBoLoaiXe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/LayToanBoLoaiXe", ReplyAction="http://tempuri.org/IQuanLyXeMay/LayToanBoLoaiXeResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eLoaiXe[]> LayToanBoLoaiXeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/LayLoaiTheoMa", ReplyAction="http://tempuri.org/IQuanLyXeMay/LayLoaiTheoMaResponse")]
        Presentation.DungWCFQuanLyXeMay.eLoaiXe LayLoaiTheoMa(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/LayLoaiTheoMa", ReplyAction="http://tempuri.org/IQuanLyXeMay/LayLoaiTheoMaResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eLoaiXe> LayLoaiTheoMaAsync(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/ThemXe", ReplyAction="http://tempuri.org/IQuanLyXeMay/ThemXeResponse")]
        int ThemXe(Presentation.DungWCFQuanLyXeMay.eXeMay xemaymoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/ThemXe", ReplyAction="http://tempuri.org/IQuanLyXeMay/ThemXeResponse")]
        System.Threading.Tasks.Task<int> ThemXeAsync(Presentation.DungWCFQuanLyXeMay.eXeMay xemaymoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/KiemTraXeMay", ReplyAction="http://tempuri.org/IQuanLyXeMay/KiemTraXeMayResponse")]
        bool KiemTraXeMay(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/KiemTraXeMay", ReplyAction="http://tempuri.org/IQuanLyXeMay/KiemTraXeMayResponse")]
        System.Threading.Tasks.Task<bool> KiemTraXeMayAsync(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/XoaXe", ReplyAction="http://tempuri.org/IQuanLyXeMay/XoaXeResponse")]
        int XoaXe(Presentation.DungWCFQuanLyXeMay.eXeMay xe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/XoaXe", ReplyAction="http://tempuri.org/IQuanLyXeMay/XoaXeResponse")]
        System.Threading.Tasks.Task<int> XoaXeAsync(Presentation.DungWCFQuanLyXeMay.eXeMay xe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/SuaXeMay", ReplyAction="http://tempuri.org/IQuanLyXeMay/SuaXeMayResponse")]
        int SuaXeMay(Presentation.DungWCFQuanLyXeMay.eXeMay xe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/SuaXeMay", ReplyAction="http://tempuri.org/IQuanLyXeMay/SuaXeMayResponse")]
        System.Threading.Tasks.Task<int> SuaXeMayAsync(Presentation.DungWCFQuanLyXeMay.eXeMay xe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/LayLoaiXeTheoTenLoai", ReplyAction="http://tempuri.org/IQuanLyXeMay/LayLoaiXeTheoTenLoaiResponse")]
        Presentation.DungWCFQuanLyXeMay.eLoaiXe LayLoaiXeTheoTenLoai(string tenLoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/LayLoaiXeTheoTenLoai", ReplyAction="http://tempuri.org/IQuanLyXeMay/LayLoaiXeTheoTenLoaiResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eLoaiXe> LayLoaiXeTheoTenLoaiAsync(string tenLoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/CapNhatSoLuongXe", ReplyAction="http://tempuri.org/IQuanLyXeMay/CapNhatSoLuongXeResponse")]
        int CapNhatSoLuongXe(Presentation.DungWCFQuanLyXeMay.eXeMay xe, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/CapNhatSoLuongXe", ReplyAction="http://tempuri.org/IQuanLyXeMay/CapNhatSoLuongXeResponse")]
        System.Threading.Tasks.Task<int> CapNhatSoLuongXeAsync(Presentation.DungWCFQuanLyXeMay.eXeMay xe, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/KiemTraDangNhap", ReplyAction="http://tempuri.org/IQuanLyXeMay/KiemTraDangNhapResponse")]
        Presentation.DungWCFQuanLyXeMay.eNhanVien KiemTraDangNhap(string taiKhoan, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/KiemTraDangNhap", ReplyAction="http://tempuri.org/IQuanLyXeMay/KiemTraDangNhapResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eNhanVien> KiemTraDangNhapAsync(string taiKhoan, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/themHoaDon", ReplyAction="http://tempuri.org/IQuanLyXeMay/themHoaDonResponse")]
        int themHoaDon(Presentation.DungWCFQuanLyXeMay.eHoaDon eHD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/themHoaDon", ReplyAction="http://tempuri.org/IQuanLyXeMay/themHoaDonResponse")]
        System.Threading.Tasks.Task<int> themHoaDonAsync(Presentation.DungWCFQuanLyXeMay.eHoaDon eHD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/thongKeBanChay", ReplyAction="http://tempuri.org/IQuanLyXeMay/thongKeBanChayResponse")]
        Presentation.DungWCFQuanLyXeMay.eThongKeBanChay[] thongKeBanChay(System.DateTime tuNgay, System.DateTime denNgay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/thongKeBanChay", ReplyAction="http://tempuri.org/IQuanLyXeMay/thongKeBanChayResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eThongKeBanChay[]> thongKeBanChayAsync(System.DateTime tuNgay, System.DateTime denNgay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/thongKeKhachMuaNhieu", ReplyAction="http://tempuri.org/IQuanLyXeMay/thongKeKhachMuaNhieuResponse")]
        Presentation.DungWCFQuanLyXeMay.eThongKeKhachMuaNhieu[] thongKeKhachMuaNhieu(System.DateTime tuNgay, System.DateTime denNgay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/thongKeKhachMuaNhieu", ReplyAction="http://tempuri.org/IQuanLyXeMay/thongKeKhachMuaNhieuResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eThongKeKhachMuaNhieu[]> thongKeKhachMuaNhieuAsync(System.DateTime tuNgay, System.DateTime denNgay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/thongKeDoanhThu", ReplyAction="http://tempuri.org/IQuanLyXeMay/thongKeDoanhThuResponse")]
        Presentation.DungWCFQuanLyXeMay.eThongKeDoanhThu[] thongKeDoanhThu(System.DateTime tuNgay, System.DateTime denNgay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/thongKeDoanhThu", ReplyAction="http://tempuri.org/IQuanLyXeMay/thongKeDoanhThuResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eThongKeDoanhThu[]> thongKeDoanhThuAsync(System.DateTime tuNgay, System.DateTime denNgay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/TimKhachHangTheoSDT", ReplyAction="http://tempuri.org/IQuanLyXeMay/TimKhachHangTheoSDTResponse")]
        Presentation.DungWCFQuanLyXeMay.eKhachHang TimKhachHangTheoSDT(string sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/TimKhachHangTheoSDT", ReplyAction="http://tempuri.org/IQuanLyXeMay/TimKhachHangTheoSDTResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eKhachHang> TimKhachHangTheoSDTAsync(string sdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/TimKhachHangTheoMa", ReplyAction="http://tempuri.org/IQuanLyXeMay/TimKhachHangTheoMaResponse")]
        Presentation.DungWCFQuanLyXeMay.eKhachHang TimKhachHangTheoMa(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/TimKhachHangTheoMa", ReplyAction="http://tempuri.org/IQuanLyXeMay/TimKhachHangTheoMaResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eKhachHang> TimKhachHangTheoMaAsync(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/TimKhachHangTheoTen", ReplyAction="http://tempuri.org/IQuanLyXeMay/TimKhachHangTheoTenResponse")]
        Presentation.DungWCFQuanLyXeMay.eKhachHang TimKhachHangTheoTen(string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/TimKhachHangTheoTen", ReplyAction="http://tempuri.org/IQuanLyXeMay/TimKhachHangTheoTenResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eKhachHang> TimKhachHangTheoTenAsync(string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/PhatSinhMaKH", ReplyAction="http://tempuri.org/IQuanLyXeMay/PhatSinhMaKHResponse")]
        string PhatSinhMaKH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/PhatSinhMaKH", ReplyAction="http://tempuri.org/IQuanLyXeMay/PhatSinhMaKHResponse")]
        System.Threading.Tasks.Task<string> PhatSinhMaKHAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/PhatSinhMaXe", ReplyAction="http://tempuri.org/IQuanLyXeMay/PhatSinhMaXeResponse")]
        string PhatSinhMaXe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/PhatSinhMaXe", ReplyAction="http://tempuri.org/IQuanLyXeMay/PhatSinhMaXeResponse")]
        System.Threading.Tasks.Task<string> PhatSinhMaXeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/PhatSinhMaNhanVien", ReplyAction="http://tempuri.org/IQuanLyXeMay/PhatSinhMaNhanVienResponse")]
        string PhatSinhMaNhanVien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/PhatSinhMaNhanVien", ReplyAction="http://tempuri.org/IQuanLyXeMay/PhatSinhMaNhanVienResponse")]
        System.Threading.Tasks.Task<string> PhatSinhMaNhanVienAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/PhatSinhMaHoaDon", ReplyAction="http://tempuri.org/IQuanLyXeMay/PhatSinhMaHoaDonResponse")]
        string PhatSinhMaHoaDon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/PhatSinhMaHoaDon", ReplyAction="http://tempuri.org/IQuanLyXeMay/PhatSinhMaHoaDonResponse")]
        System.Threading.Tasks.Task<string> PhatSinhMaHoaDonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/TimXeTheoTen", ReplyAction="http://tempuri.org/IQuanLyXeMay/TimXeTheoTenResponse")]
        Presentation.DungWCFQuanLyXeMay.eXeMay TimXeTheoTen(string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/TimXeTheoTen", ReplyAction="http://tempuri.org/IQuanLyXeMay/TimXeTheoTenResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eXeMay> TimXeTheoTenAsync(string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/TimXeTheoMa", ReplyAction="http://tempuri.org/IQuanLyXeMay/TimXeTheoMaResponse")]
        Presentation.DungWCFQuanLyXeMay.eXeMay TimXeTheoMa(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/TimXeTheoMa", ReplyAction="http://tempuri.org/IQuanLyXeMay/TimXeTheoMaResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eXeMay> TimXeTheoMaAsync(string ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/ThemChiThiet", ReplyAction="http://tempuri.org/IQuanLyXeMay/ThemChiThietResponse")]
        int ThemChiThiet(Presentation.DungWCFQuanLyXeMay.eChiTiet ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/ThemChiThiet", ReplyAction="http://tempuri.org/IQuanLyXeMay/ThemChiThietResponse")]
        System.Threading.Tasks.Task<int> ThemChiThietAsync(Presentation.DungWCFQuanLyXeMay.eChiTiet ct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/GiamSoLuongXe", ReplyAction="http://tempuri.org/IQuanLyXeMay/GiamSoLuongXeResponse")]
        int GiamSoLuongXe(Presentation.DungWCFQuanLyXeMay.eXeMay xe, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/GiamSoLuongXe", ReplyAction="http://tempuri.org/IQuanLyXeMay/GiamSoLuongXeResponse")]
        System.Threading.Tasks.Task<int> GiamSoLuongXeAsync(Presentation.DungWCFQuanLyXeMay.eXeMay xe, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/layToanBoHoaDon", ReplyAction="http://tempuri.org/IQuanLyXeMay/layToanBoHoaDonResponse")]
        Presentation.DungWCFQuanLyXeMay.eHoaDon[] layToanBoHoaDon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/layToanBoHoaDon", ReplyAction="http://tempuri.org/IQuanLyXeMay/layToanBoHoaDonResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eHoaDon[]> layToanBoHoaDonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/layChiTietTheoMa", ReplyAction="http://tempuri.org/IQuanLyXeMay/layChiTietTheoMaResponse")]
        Presentation.DungWCFQuanLyXeMay.eChiTiet[] layChiTietTheoMa(string maHD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/layChiTietTheoMa", ReplyAction="http://tempuri.org/IQuanLyXeMay/layChiTietTheoMaResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eChiTiet[]> layChiTietTheoMaAsync(string maHD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/timNhanVienTheoMa", ReplyAction="http://tempuri.org/IQuanLyXeMay/timNhanVienTheoMaResponse")]
        Presentation.DungWCFQuanLyXeMay.eNhanVien timNhanVienTheoMa(string maNV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/timNhanVienTheoMa", ReplyAction="http://tempuri.org/IQuanLyXeMay/timNhanVienTheoMaResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eNhanVien> timNhanVienTheoMaAsync(string maNV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/TimNhanVienTheoTen", ReplyAction="http://tempuri.org/IQuanLyXeMay/TimNhanVienTheoTenResponse")]
        Presentation.DungWCFQuanLyXeMay.eNhanVien TimNhanVienTheoTen(string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuanLyXeMay/TimNhanVienTheoTen", ReplyAction="http://tempuri.org/IQuanLyXeMay/TimNhanVienTheoTenResponse")]
        System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eNhanVien> TimNhanVienTheoTenAsync(string ten);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuanLyXeMayChannel : Presentation.DungWCFQuanLyXeMay.IQuanLyXeMay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuanLyXeMayClient : System.ServiceModel.ClientBase<Presentation.DungWCFQuanLyXeMay.IQuanLyXeMay>, Presentation.DungWCFQuanLyXeMay.IQuanLyXeMay {
        
        public QuanLyXeMayClient() {
        }
        
        public QuanLyXeMayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuanLyXeMayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuanLyXeMayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuanLyXeMayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Presentation.DungWCFQuanLyXeMay.eNhanVien[] LayToanBoNhanVien() {
            return base.Channel.LayToanBoNhanVien();
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eNhanVien[]> LayToanBoNhanVienAsync() {
            return base.Channel.LayToanBoNhanVienAsync();
        }
        
        public int ThemNhanVien(Presentation.DungWCFQuanLyXeMay.eNhanVien nv) {
            return base.Channel.ThemNhanVien(nv);
        }
        
        public System.Threading.Tasks.Task<int> ThemNhanVienAsync(Presentation.DungWCFQuanLyXeMay.eNhanVien nv) {
            return base.Channel.ThemNhanVienAsync(nv);
        }
        
        public bool KiemTraNhanVien(string ma) {
            return base.Channel.KiemTraNhanVien(ma);
        }
        
        public System.Threading.Tasks.Task<bool> KiemTraNhanVienAsync(string ma) {
            return base.Channel.KiemTraNhanVienAsync(ma);
        }
        
        public int SuaNhanVien(Presentation.DungWCFQuanLyXeMay.eNhanVien nv) {
            return base.Channel.SuaNhanVien(nv);
        }
        
        public System.Threading.Tasks.Task<int> SuaNhanVienAsync(Presentation.DungWCFQuanLyXeMay.eNhanVien nv) {
            return base.Channel.SuaNhanVienAsync(nv);
        }
        
        public int XoaNhanVien(Presentation.DungWCFQuanLyXeMay.eNhanVien nv) {
            return base.Channel.XoaNhanVien(nv);
        }
        
        public System.Threading.Tasks.Task<int> XoaNhanVienAsync(Presentation.DungWCFQuanLyXeMay.eNhanVien nv) {
            return base.Channel.XoaNhanVienAsync(nv);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eKhachHang[] LayToanBoKhachHang() {
            return base.Channel.LayToanBoKhachHang();
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eKhachHang[]> LayToanBoKhachHangAsync() {
            return base.Channel.LayToanBoKhachHangAsync();
        }
        
        public int ThemKhachHang(Presentation.DungWCFQuanLyXeMay.eKhachHang kh) {
            return base.Channel.ThemKhachHang(kh);
        }
        
        public System.Threading.Tasks.Task<int> ThemKhachHangAsync(Presentation.DungWCFQuanLyXeMay.eKhachHang kh) {
            return base.Channel.ThemKhachHangAsync(kh);
        }
        
        public int SuaKhachHang(Presentation.DungWCFQuanLyXeMay.eKhachHang kh) {
            return base.Channel.SuaKhachHang(kh);
        }
        
        public System.Threading.Tasks.Task<int> SuaKhachHangAsync(Presentation.DungWCFQuanLyXeMay.eKhachHang kh) {
            return base.Channel.SuaKhachHangAsync(kh);
        }
        
        public int XoaKhachHang(Presentation.DungWCFQuanLyXeMay.eKhachHang kh) {
            return base.Channel.XoaKhachHang(kh);
        }
        
        public System.Threading.Tasks.Task<int> XoaKhachHangAsync(Presentation.DungWCFQuanLyXeMay.eKhachHang kh) {
            return base.Channel.XoaKhachHangAsync(kh);
        }
        
        public bool KiemTraKhachHang(string ma) {
            return base.Channel.KiemTraKhachHang(ma);
        }
        
        public System.Threading.Tasks.Task<bool> KiemTraKhachHangAsync(string ma) {
            return base.Channel.KiemTraKhachHangAsync(ma);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eXeMay[] LayToanBoXeMay() {
            return base.Channel.LayToanBoXeMay();
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eXeMay[]> LayToanBoXeMayAsync() {
            return base.Channel.LayToanBoXeMayAsync();
        }
        
        public Presentation.DungWCFQuanLyXeMay.eLoaiXe[] LayToanBoLoaiXe() {
            return base.Channel.LayToanBoLoaiXe();
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eLoaiXe[]> LayToanBoLoaiXeAsync() {
            return base.Channel.LayToanBoLoaiXeAsync();
        }
        
        public Presentation.DungWCFQuanLyXeMay.eLoaiXe LayLoaiTheoMa(string ma) {
            return base.Channel.LayLoaiTheoMa(ma);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eLoaiXe> LayLoaiTheoMaAsync(string ma) {
            return base.Channel.LayLoaiTheoMaAsync(ma);
        }
        
        public int ThemXe(Presentation.DungWCFQuanLyXeMay.eXeMay xemaymoi) {
            return base.Channel.ThemXe(xemaymoi);
        }
        
        public System.Threading.Tasks.Task<int> ThemXeAsync(Presentation.DungWCFQuanLyXeMay.eXeMay xemaymoi) {
            return base.Channel.ThemXeAsync(xemaymoi);
        }
        
        public bool KiemTraXeMay(string ma) {
            return base.Channel.KiemTraXeMay(ma);
        }
        
        public System.Threading.Tasks.Task<bool> KiemTraXeMayAsync(string ma) {
            return base.Channel.KiemTraXeMayAsync(ma);
        }
        
        public int XoaXe(Presentation.DungWCFQuanLyXeMay.eXeMay xe) {
            return base.Channel.XoaXe(xe);
        }
        
        public System.Threading.Tasks.Task<int> XoaXeAsync(Presentation.DungWCFQuanLyXeMay.eXeMay xe) {
            return base.Channel.XoaXeAsync(xe);
        }
        
        public int SuaXeMay(Presentation.DungWCFQuanLyXeMay.eXeMay xe) {
            return base.Channel.SuaXeMay(xe);
        }
        
        public System.Threading.Tasks.Task<int> SuaXeMayAsync(Presentation.DungWCFQuanLyXeMay.eXeMay xe) {
            return base.Channel.SuaXeMayAsync(xe);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eLoaiXe LayLoaiXeTheoTenLoai(string tenLoai) {
            return base.Channel.LayLoaiXeTheoTenLoai(tenLoai);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eLoaiXe> LayLoaiXeTheoTenLoaiAsync(string tenLoai) {
            return base.Channel.LayLoaiXeTheoTenLoaiAsync(tenLoai);
        }
        
        public int CapNhatSoLuongXe(Presentation.DungWCFQuanLyXeMay.eXeMay xe, int soluong) {
            return base.Channel.CapNhatSoLuongXe(xe, soluong);
        }
        
        public System.Threading.Tasks.Task<int> CapNhatSoLuongXeAsync(Presentation.DungWCFQuanLyXeMay.eXeMay xe, int soluong) {
            return base.Channel.CapNhatSoLuongXeAsync(xe, soluong);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eNhanVien KiemTraDangNhap(string taiKhoan, string matKhau) {
            return base.Channel.KiemTraDangNhap(taiKhoan, matKhau);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eNhanVien> KiemTraDangNhapAsync(string taiKhoan, string matKhau) {
            return base.Channel.KiemTraDangNhapAsync(taiKhoan, matKhau);
        }
        
        public int themHoaDon(Presentation.DungWCFQuanLyXeMay.eHoaDon eHD) {
            return base.Channel.themHoaDon(eHD);
        }
        
        public System.Threading.Tasks.Task<int> themHoaDonAsync(Presentation.DungWCFQuanLyXeMay.eHoaDon eHD) {
            return base.Channel.themHoaDonAsync(eHD);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eThongKeBanChay[] thongKeBanChay(System.DateTime tuNgay, System.DateTime denNgay) {
            return base.Channel.thongKeBanChay(tuNgay, denNgay);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eThongKeBanChay[]> thongKeBanChayAsync(System.DateTime tuNgay, System.DateTime denNgay) {
            return base.Channel.thongKeBanChayAsync(tuNgay, denNgay);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eThongKeKhachMuaNhieu[] thongKeKhachMuaNhieu(System.DateTime tuNgay, System.DateTime denNgay) {
            return base.Channel.thongKeKhachMuaNhieu(tuNgay, denNgay);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eThongKeKhachMuaNhieu[]> thongKeKhachMuaNhieuAsync(System.DateTime tuNgay, System.DateTime denNgay) {
            return base.Channel.thongKeKhachMuaNhieuAsync(tuNgay, denNgay);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eThongKeDoanhThu[] thongKeDoanhThu(System.DateTime tuNgay, System.DateTime denNgay) {
            return base.Channel.thongKeDoanhThu(tuNgay, denNgay);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eThongKeDoanhThu[]> thongKeDoanhThuAsync(System.DateTime tuNgay, System.DateTime denNgay) {
            return base.Channel.thongKeDoanhThuAsync(tuNgay, denNgay);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eKhachHang TimKhachHangTheoSDT(string sdt) {
            return base.Channel.TimKhachHangTheoSDT(sdt);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eKhachHang> TimKhachHangTheoSDTAsync(string sdt) {
            return base.Channel.TimKhachHangTheoSDTAsync(sdt);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eKhachHang TimKhachHangTheoMa(string ma) {
            return base.Channel.TimKhachHangTheoMa(ma);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eKhachHang> TimKhachHangTheoMaAsync(string ma) {
            return base.Channel.TimKhachHangTheoMaAsync(ma);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eKhachHang TimKhachHangTheoTen(string ten) {
            return base.Channel.TimKhachHangTheoTen(ten);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eKhachHang> TimKhachHangTheoTenAsync(string ten) {
            return base.Channel.TimKhachHangTheoTenAsync(ten);
        }
        
        public string PhatSinhMaKH() {
            return base.Channel.PhatSinhMaKH();
        }
        
        public System.Threading.Tasks.Task<string> PhatSinhMaKHAsync() {
            return base.Channel.PhatSinhMaKHAsync();
        }
        
        public string PhatSinhMaXe() {
            return base.Channel.PhatSinhMaXe();
        }
        
        public System.Threading.Tasks.Task<string> PhatSinhMaXeAsync() {
            return base.Channel.PhatSinhMaXeAsync();
        }
        
        public string PhatSinhMaNhanVien() {
            return base.Channel.PhatSinhMaNhanVien();
        }
        
        public System.Threading.Tasks.Task<string> PhatSinhMaNhanVienAsync() {
            return base.Channel.PhatSinhMaNhanVienAsync();
        }
        
        public string PhatSinhMaHoaDon() {
            return base.Channel.PhatSinhMaHoaDon();
        }
        
        public System.Threading.Tasks.Task<string> PhatSinhMaHoaDonAsync() {
            return base.Channel.PhatSinhMaHoaDonAsync();
        }
        
        public Presentation.DungWCFQuanLyXeMay.eXeMay TimXeTheoTen(string ten) {
            return base.Channel.TimXeTheoTen(ten);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eXeMay> TimXeTheoTenAsync(string ten) {
            return base.Channel.TimXeTheoTenAsync(ten);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eXeMay TimXeTheoMa(string ma) {
            return base.Channel.TimXeTheoMa(ma);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eXeMay> TimXeTheoMaAsync(string ma) {
            return base.Channel.TimXeTheoMaAsync(ma);
        }
        
        public int ThemChiThiet(Presentation.DungWCFQuanLyXeMay.eChiTiet ct) {
            return base.Channel.ThemChiThiet(ct);
        }
        
        public System.Threading.Tasks.Task<int> ThemChiThietAsync(Presentation.DungWCFQuanLyXeMay.eChiTiet ct) {
            return base.Channel.ThemChiThietAsync(ct);
        }
        
        public int GiamSoLuongXe(Presentation.DungWCFQuanLyXeMay.eXeMay xe, int soluong) {
            return base.Channel.GiamSoLuongXe(xe, soluong);
        }
        
        public System.Threading.Tasks.Task<int> GiamSoLuongXeAsync(Presentation.DungWCFQuanLyXeMay.eXeMay xe, int soluong) {
            return base.Channel.GiamSoLuongXeAsync(xe, soluong);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eHoaDon[] layToanBoHoaDon() {
            return base.Channel.layToanBoHoaDon();
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eHoaDon[]> layToanBoHoaDonAsync() {
            return base.Channel.layToanBoHoaDonAsync();
        }
        
        public Presentation.DungWCFQuanLyXeMay.eChiTiet[] layChiTietTheoMa(string maHD) {
            return base.Channel.layChiTietTheoMa(maHD);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eChiTiet[]> layChiTietTheoMaAsync(string maHD) {
            return base.Channel.layChiTietTheoMaAsync(maHD);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eNhanVien timNhanVienTheoMa(string maNV) {
            return base.Channel.timNhanVienTheoMa(maNV);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eNhanVien> timNhanVienTheoMaAsync(string maNV) {
            return base.Channel.timNhanVienTheoMaAsync(maNV);
        }
        
        public Presentation.DungWCFQuanLyXeMay.eNhanVien TimNhanVienTheoTen(string ten) {
            return base.Channel.TimNhanVienTheoTen(ten);
        }
        
        public System.Threading.Tasks.Task<Presentation.DungWCFQuanLyXeMay.eNhanVien> TimNhanVienTheoTenAsync(string ten) {
            return base.Channel.TimNhanVienTheoTenAsync(ten);
        }
    }
}
